import { type XPParseResult, SHAPE_CODES } from './xp-parser';

function f(v: number | undefined | null, d = 2): string {
  return v == null || v === 0 ? '0' : typeof v === 'number' ? v.toFixed(d) : String(v);
}
function pd(s: string | number, w: number): string { return String(s).padEnd(w); }

export function buildINP(p: XPParseResult): string {
  const jc = p.jobControl;
  const metric = jc.METRIC === '1';
  let inp = `;; SWMM5 .inp converted from XPSWMM .xp file
;; Generated by XPSWMM Card Reader
;; Source format: ${p.format} | Original title: ${p.title || '(none)'}

[TITLE]
;;Project Title/Notes
${p.title || 'Converted from XPSWMM .xp file'}

[OPTIONS]
FLOW_UNITS           ${metric ? 'CMS' : 'CFS'}
INFILTRATION         HORTON
FLOW_ROUTING         ${jc.KINE === '3' ? 'KINWAVE' : jc.KINE === '4' ? 'DIFWAVE' : 'DYNWAVE'}
LINK_OFFSETS         DEPTH
MIN_SLOPE            0.0
ALLOW_PONDING        NO
SKIP_STEADY_STATE    NO
`;
  if (jc.DELT) inp += `ROUTING_STEP         00:00:${String(Math.round(parseFloat(jc.DELT))).padStart(2, '0')}\n`;
  if (jc.DELT) inp += `VARIABLE_STEP        0.75\n`;
  inp += `INERTIAL_DAMPING     ${jc.KINE === '1' ? 'FULL' : jc.KINE === '2' ? 'NONE' : 'PARTIAL'}\n`;
  inp += `NORMAL_FLOW_LIMITED  BOTH\n`;
  if (jc.MFAIL) inp += `MAX_TRIALS           ${jc.MFAIL}\n`;
  if (jc.FUDGE) inp += `HEAD_TOLERANCE       ${jc.FUDGE}\n`;
  inp += '\n';

  const jn = p.nodes.filter(n => n.type === 'Junction');
  if (jn.length) {
    inp += `[JUNCTIONS]\n;;Name           Elev       MaxDepth   InitDepth  SurDepth   Aponded\n;;-------------- ---------- ---------- ---------- ---------- ----------\n`;
    jn.forEach(n => {
      const maxD = n.ztop && n.grelev ? (n.ztop - n.grelev) : 0;
      inp += `${pd(n.name, 16)} ${pd(f(n.grelev), 10)} ${pd(f(maxD), 10)} ${pd(f(n.y0), 10)} 0          0\n`;
    });
    inp += '\n';
  }

  const of = p.nodes.filter(n => n.type === 'Outfall');
  if (of.length) {
    inp += `[OUTFALLS]\n;;Name           Elev       Type       Stage      Gated\n;;-------------- ---------- ---------- ---------- -----\n`;
    of.forEach(n => {
      let otype = 'FREE';
      if (n.ko === 2) otype = 'FIXED';
      else if (n.ko === 3 || n.ko === 4) otype = 'TIDAL';
      else if (n.ko === 5 || n.ko === 6) otype = 'TIMESERIES';
      const stage = (n.ko === 2 && n.delta) ? f(n.delta) : '';
      inp += `${pd(n.name, 16)} ${pd(f(n.grelev), 10)} ${pd(otype, 10)} ${pd(stage, 10)} NO\n`;
    });
    inp += '\n';
  }

  const st = p.nodes.filter(n => n.type === 'Storage');
  if (st.length) {
    inp += `[STORAGE]\n;;Name           Elev       MaxDepth   InitDepth  Shape      Curve/Params\n;;-------------- ---------- ---------- ---------- ---------- ----------\n`;
    st.forEach(n => {
      const maxD = n.ztop && n.grelev ? (n.ztop - n.grelev) : 0;
      const area = n.astore || 0;
      inp += `${pd(n.name, 16)} ${pd(f(n.grelev), 10)} ${pd(f(maxD), 10)} ${pd(f(n.y0), 10)} FUNCTIONAL ${f(area)} 0          0\n`;
    });
    inp += '\n';
  }

  const cd = p.links.filter(l => l.type === 'Conduit');
  if (cd.length) {
    inp += `[CONDUITS]\n;;Name           From             To               Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow\n;;-------------- ---------------- ---------------- ---------- ---------- ---------- ---------- ---------- ----------\n`;
    cd.forEach(l => {
      inp += `${pd(l.name, 16)} ${pd(l.usNode || '?', 16)} ${pd(l.dsNode || '?', 16)} ${pd(f(l.len), 10)} ${pd(f(l.rough, 4), 10)} ${pd(f(l.zp1), 10)} ${pd(f(l.zp2), 10)} 0          0\n`;
    });
    inp += '\n';
  }

  const orf = p.links.filter(l => l.type === 'Orifice');
  if (orf.length) {
    inp += `[ORIFICES]\n;;Name           From             To               Type       Offset     Qcoeff     Gated    CloseTime\n;;-------------- ---------------- ---------------- ---------- ---------- ---------- -------- ----------\n`;
    orf.forEach(l => {
      const otype = (l.onklass === 2) ? 'CIRCULAR' : 'SIDE';
      const coeff = l.corif || 0.65;
      const off = l.zp || l.zp1 || 0;
      inp += `${pd(l.name, 16)} ${pd(l.usNode || '?', 16)} ${pd(l.dsNode || '?', 16)} ${pd(otype, 10)} ${pd(f(off), 10)} ${pd(f(coeff, 3), 10)} NO       0\n`;
    });
    inp += '\n';
  }

  const wrs = p.links.filter(l => l.type === 'Weir');
  if (wrs.length) {
    inp += `[WEIRS]\n;;Name           From             To               Type       CrestHt    Qcoeff     Gated    EndCon   EndCoeff   Surcharge\n;;-------------- ---------------- ---------------- ---------- ---------- ---------- -------- -------- ---------- ----------\n`;
    wrs.forEach(l => {
      const swmm5Type: Record<number, string> = { 1: 'TRANSVERSE', 2: 'SIDEFLOW', 3: 'V-NOTCH', 4: 'TRAPEZOIDAL' };
      const t = swmm5Type[l.kweir || 0] || 'TRANSVERSE';
      const coeff = l.wcoeff || 1.84;
      inp += `${pd(l.name, 16)} ${pd(l.usNode || '?', 16)} ${pd(l.dsNode || '?', 16)} ${pd(t, 10)} ${pd(f(l.ycrest), 10)} ${pd(f(coeff, 3), 10)} NO       0        0          YES\n`;
    });
    inp += '\n';
  }

  const pmp = p.links.filter(l => l.type === 'Pump');
  if (pmp.length) {
    inp += `[PUMPS]\n;;Name           From             To               PumpCurve  Status   Startup    Shutoff\n;;-------------- ---------------- ---------------- ---------- -------- ---------- ----------\n`;
    pmp.forEach(l => {
      const curve = l.psel ? l.psel.trim() : '*';
      inp += `${pd(l.name, 16)} ${pd(l.usNode || '?', 16)} ${pd(l.dsNode || '?', 16)} ${pd(curve, 10)} ON       ${pd(f(l.pon), 10)} ${pd(f(l.poff), 10)}\n`;
    });
    inp += '\n';
  }

  const xsLinks = [...cd, ...orf, ...wrs];
  if (xsLinks.length) {
    inp += `[XSECTIONS]\n;;Link           Shape        Geom1      Geom2      Geom3      Geom4      Barrels\n;;-------------- ------------ ---------- ---------- ---------- ---------- ----------\n`;
    const shapeMap: Record<number, string> = {
      1: 'CIRCULAR', 2: 'RECT_CLOSED', 3: 'HORSESHOE', 4: 'EGG', 5: 'BASKETHANDLE',
      6: 'TRAPEZOIDAL', 7: 'POWER', 8: 'IRREGULAR', 9: 'GOTHIC', 10: 'CATENARY',
      11: 'SEMIELLIPTICAL', 12: 'BASKETHANDLE', 13: 'CUSTOM', 14: 'ARCH',
      16: 'PARABOLIC', 17: 'RECT_CLOSED', 18: 'SEMICIRCULAR', 19: 'RECT_ROUND', 20: 'RECT_TRIANGULAR'
    };
    cd.forEach(l => {
      const s = shapeMap[l.nklass || 0] || 'CIRCULAR';
      inp += `${pd(l.name, 16)} ${pd(s, 12)} ${pd(f(l.deep), 10)} ${pd(f(l.wide), 10)} 0          0          ${l.barrel || 1}\n`;
    });
    orf.forEach(l => {
      const s = (l.onklass === 2) ? 'CIRCULAR' : 'RECT_CLOSED';
      const geom1 = l.dorif || l.deep || 0;
      inp += `${pd(l.name, 16)} ${pd(s, 12)} ${pd(f(geom1), 10)} 0          0          0          \n`;
    });
    wrs.forEach(l => {
      const geom1 = l.ytop ? (l.ytop - (l.ycrest || 0)) : 0;
      const geom2 = l.wlen || 0;
      inp += `${pd(l.name, 16)} RECT_OPEN    ${pd(f(geom1), 10)} ${pd(f(geom2), 10)} 0          0          \n`;
    });
    inp += '\n';
  }

  if (cd.length) {
    inp += `[LOSSES]\n;;Link           Inlet      Outlet     Average    Flap Gate\n;;-------------- ---------- ---------- ---------- ----------\n`;
    cd.forEach(l => {
      inp += `${pd(l.name, 16)} 0          0          0          NO\n`;
    });
    inp += '\n';
  }

  const inflowNodes = p.nodes.filter(n => n.qinst && n.qinst > 0);
  if (inflowNodes.length) {
    inp += `[INFLOWS]\n;;Node           Constituent  Time Series      Type     Mfactor  Sfactor  Baseline Pattern\n;;-------------- ------------ ---------------- -------- -------- -------- -------- --------\n`;
    inflowNodes.forEach(n => {
      inp += `${pd(n.name, 16)} FLOW         ""               FLOW     1.0      1.0      ${f(n.qinst)}\n`;
    });
    inp += '\n';
  }

  const cn = p.nodes.filter(n => n.x || n.y);
  if (cn.length) {
    inp += `[COORDINATES]\n;;Node           X-Coord            Y-Coord\n;;-------------- ------------------ ------------------\n`;
    cn.forEach(n => { inp += `${pd(n.name, 16)} ${pd(f(n.x, 2), 18)} ${pd(f(n.y, 2), 18)}\n`; });
    inp += '\n';

    const xs = cn.map(n => n.x), ys = cn.map(n => n.y);
    inp += `[MAP]\nDIMENSIONS ${Math.min(...xs).toFixed(2)} ${Math.min(...ys).toFixed(2)} ${Math.max(...xs).toFixed(2)} ${Math.max(...ys).toFixed(2)}\nUnits      None\n\n`;
  }

  // Subcatchments
  const subs = p.subcatchments || [];
  if (subs.length) {
    inp += `[SUBCATCHMENTS]\n;;Name           Rain Gage        Outlet           Area       %Imperv    Width      %Slope     CurbLen    SnowPack\n;;-------------- ---------------- ---------------- ---------- ---------- ---------- ---------- ---------- ----------\n`;
    subs.forEach(s => {
      inp += `${pd(s.name, 16)} ${pd(s.rainGage || '*', 16)} ${pd(s.outlet || '?', 16)} ${pd(f(s.area), 10)} ${pd(f(s.imperv), 10)} ${pd(f(s.width), 10)} ${pd(f(s.slope), 10)} 0          \n`;
    });
    inp += '\n';
  }

  if (subs.length) {
    inp += `[SUBAREAS]\n;;Subcatchment    N-Imperv   N-Perv     S-Imperv   S-Perv     PctZero    RouteTo    PctRouted\n;;-------------- ---------- ---------- ---------- ---------- ---------- ---------- ----------\n`;
    subs.forEach(s => {
      inp += `${pd(s.name, 16)} ${pd(f(s.nImperv, 4), 10)} ${pd(f(s.nPerv, 4), 10)} ${pd(f(s.dsImperv, 2), 10)} ${pd(f(s.dsPerv, 2), 10)} ${pd(f(s.pctZero), 10)} ${pd(s.routeTo || 'OUTLET', 10)} 100\n`;
    });
    inp += '\n';
  }

  // Infiltration (Horton if f0 available, else Green-Ampt if conduc, else Curve Number)
  const subsWithInfil = subs.filter(s => s.f0 > 0 || s.conduc > 0 || s.curveNum > 0);
  if (subsWithInfil.length) {
    inp += `[INFILTRATION]\n;;Subcatchment    Param1     Param2     Param3     Param4     Param5\n;;-------------- ---------- ---------- ---------- ---------- ----------\n`;
    subs.forEach(s => {
      if (s.f0 > 0) {
        // Horton
        inp += `${pd(s.name, 16)} ${pd(f(s.f0), 10)} ${pd(f(s.ff), 10)} ${pd(f(s.fDecay), 10)} ${pd(f(s.fDry), 10)} ${pd(f(s.fMaxVol), 10)}\n`;
      } else if (s.conduc > 0) {
        // Green-Ampt
        inp += `${pd(s.name, 16)} ${pd(f(s.suctionHead), 10)} ${pd(f(s.conduc), 10)} ${pd(f(s.initMoisDef), 10)} 0          0\n`;
      } else if (s.curveNum > 0) {
        // Curve Number
        inp += `${pd(s.name, 16)} ${pd(f(s.curveNum), 10)} ${pd(f(s.conduc), 10)} ${pd(f(s.fDry), 10)} 0          0\n`;
      }
    });
    inp += '\n';
  }

  inp += `[REPORT]\nSUBCATCHMENTS ALL\nNODES ALL\nLINKS ALL\n`;
  return inp;
}

export function buildCSV(data: Record<string, unknown>[]): string {
  if (!data.length) return '';
  const ks = Object.keys(data[0]);
  let csv = ks.join(',') + '\n';
  data.forEach(r => {
    csv += ks.map(k => {
      const v = r[k];
      return v == null ? '' : typeof v === 'string' && v.includes(',') ? `"${v}"` : v;
    }).join(',') + '\n';
  });
  return csv;
}
