import { type XPParseResult, type XPTimeSeries, type XPPumpCurve, type XPTransect, type XPPollutant, type XPLanduse, type XPBuildup, type XPWashoff, type XPLoading, type XPControlRule, type XPLIDControl, type XPLIDUsage, type XPRDIIUnitHydrograph, type XPRDIIInflow, SHAPE_CODES } from './xp-parser';

function f(v: number | undefined | null, d = 2): string {
  return v == null || v === 0 ? '0' : typeof v === 'number' ? v.toFixed(d) : String(v);
}
function pd(s: string | number, w: number): string { return String(s).padEnd(w); }

export function buildINP(p: XPParseResult): string {
  const jc = p.jobControl;
  const metric = jc.METRIC === '1';
  let inp = `;; SWMM5 .inp converted from XPSWMM .xp file
;; Generated by XPSWMM Card Reader
;; Source format: ${p.format} | Original title: ${p.title || '(none)'}

[TITLE]
;;Project Title/Notes
${p.title || 'Converted from XPSWMM .xp file'}

[OPTIONS]
FLOW_UNITS           ${metric ? 'CMS' : 'CFS'}
INFILTRATION         HORTON
FLOW_ROUTING         ${jc.KINE === '3' ? 'KINWAVE' : jc.KINE === '4' ? 'DIFWAVE' : 'DYNWAVE'}
LINK_OFFSETS         DEPTH
MIN_SLOPE            0.0
ALLOW_PONDING        NO
SKIP_STEADY_STATE    NO
`;
  if (jc.DELT) inp += `ROUTING_STEP         00:00:${String(Math.round(parseFloat(jc.DELT))).padStart(2, '0')}\n`;
  if (jc.DELT) inp += `VARIABLE_STEP        0.75\n`;
  inp += `INERTIAL_DAMPING     ${jc.KINE === '1' ? 'FULL' : jc.KINE === '2' ? 'NONE' : 'PARTIAL'}\n`;
  inp += `NORMAL_FLOW_LIMITED  BOTH\n`;
  if (jc.MFAIL) inp += `MAX_TRIALS           ${jc.MFAIL}\n`;
  if (jc.FUDGE) inp += `HEAD_TOLERANCE       ${jc.FUDGE}\n`;
  inp += '\n';

  const jn = p.nodes.filter(n => n.type === 'Junction');
  if (jn.length) {
    inp += `[JUNCTIONS]\n;;Name           Elev       MaxDepth   InitDepth  SurDepth   Aponded\n;;-------------- ---------- ---------- ---------- ---------- ----------\n`;
    jn.forEach(n => {
      const maxD = n.ztop && n.grelev ? (n.ztop - n.grelev) : 0;
      inp += `${pd(n.name, 16)} ${pd(f(n.grelev), 10)} ${pd(f(maxD), 10)} ${pd(f(n.y0), 10)} 0          0\n`;
    });
    inp += '\n';
  }

  const of = p.nodes.filter(n => n.type === 'Outfall');
  if (of.length) {
    inp += `[OUTFALLS]\n;;Name           Elev       Type       Stage      Gated\n;;-------------- ---------- ---------- ---------- -----\n`;
    of.forEach(n => {
      let otype = 'FREE';
      if (n.ko === 2) otype = 'FIXED';
      else if (n.ko === 3 || n.ko === 4) otype = 'TIDAL';
      else if (n.ko === 5 || n.ko === 6) otype = 'TIMESERIES';
      const stage = (n.ko === 2 && n.delta) ? f(n.delta) : '';
      inp += `${pd(n.name, 16)} ${pd(f(n.grelev), 10)} ${pd(otype, 10)} ${pd(stage, 10)} NO\n`;
    });
    inp += '\n';
  }

  const st = p.nodes.filter(n => n.type === 'Storage');
  if (st.length) {
    inp += `[STORAGE]\n;;Name           Elev       MaxDepth   InitDepth  Shape      Curve/Params\n;;-------------- ---------- ---------- ---------- ---------- ----------\n`;
    st.forEach(n => {
      const maxD = n.ztop && n.grelev ? (n.ztop - n.grelev) : 0;
      const area = n.astore || 0;
      inp += `${pd(n.name, 16)} ${pd(f(n.grelev), 10)} ${pd(f(maxD), 10)} ${pd(f(n.y0), 10)} FUNCTIONAL ${f(area)} 0          0\n`;
    });
    inp += '\n';
  }

  const cd = p.links.filter(l => l.type === 'Conduit');
  if (cd.length) {
    inp += `[CONDUITS]\n;;Name           From             To               Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow\n;;-------------- ---------------- ---------------- ---------- ---------- ---------- ---------- ---------- ----------\n`;
    cd.forEach(l => {
      inp += `${pd(l.name, 16)} ${pd(l.usNode || '?', 16)} ${pd(l.dsNode || '?', 16)} ${pd(f(l.len), 10)} ${pd(f(l.rough, 4), 10)} ${pd(f(l.zp1), 10)} ${pd(f(l.zp2), 10)} 0          0\n`;
    });
    inp += '\n';
  }

  const orf = p.links.filter(l => l.type === 'Orifice');
  if (orf.length) {
    inp += `[ORIFICES]\n;;Name           From             To               Type       Offset     Qcoeff     Gated    CloseTime\n;;-------------- ---------------- ---------------- ---------- ---------- ---------- -------- ----------\n`;
    orf.forEach(l => {
      const otype = (l.onklass === 2) ? 'CIRCULAR' : 'SIDE';
      const coeff = l.corif || 0.65;
      const off = l.zp || l.zp1 || 0;
      inp += `${pd(l.name, 16)} ${pd(l.usNode || '?', 16)} ${pd(l.dsNode || '?', 16)} ${pd(otype, 10)} ${pd(f(off), 10)} ${pd(f(coeff, 3), 10)} NO       0\n`;
    });
    inp += '\n';
  }

  const wrs = p.links.filter(l => l.type === 'Weir');
  if (wrs.length) {
    inp += `[WEIRS]\n;;Name           From             To               Type       CrestHt    Qcoeff     Gated    EndCon   EndCoeff   Surcharge\n;;-------------- ---------------- ---------------- ---------- ---------- ---------- -------- -------- ---------- ----------\n`;
    wrs.forEach(l => {
      const swmm5Type: Record<number, string> = { 1: 'TRANSVERSE', 2: 'SIDEFLOW', 3: 'V-NOTCH', 4: 'TRAPEZOIDAL' };
      const t = swmm5Type[l.kweir || 0] || 'TRANSVERSE';
      const coeff = l.wcoeff || 1.84;
      inp += `${pd(l.name, 16)} ${pd(l.usNode || '?', 16)} ${pd(l.dsNode || '?', 16)} ${pd(t, 10)} ${pd(f(l.ycrest), 10)} ${pd(f(coeff, 3), 10)} NO       0        0          YES\n`;
    });
    inp += '\n';
  }

  const pmp = p.links.filter(l => l.type === 'Pump');
  if (pmp.length) {
    inp += `[PUMPS]\n;;Name           From             To               PumpCurve  Status   Startup    Shutoff\n;;-------------- ---------------- ---------------- ---------- -------- ---------- ----------\n`;
    pmp.forEach(l => {
      const curve = l.psel ? l.psel.trim() : '*';
      inp += `${pd(l.name, 16)} ${pd(l.usNode || '?', 16)} ${pd(l.dsNode || '?', 16)} ${pd(curve, 10)} ON       ${pd(f(l.pon), 10)} ${pd(f(l.poff), 10)}\n`;
    });
    inp += '\n';
  }

  // Pump Curves
  const curves = p.pumpCurves || [];
  if (curves.length) {
    inp += `[CURVES]\n;;Name           Type       X-Value    Y-Value\n;;-------------- ---------- ---------- ----------\n`;
    curves.forEach(c => {
      if (c.points.length > 0) {
        c.points.forEach((pt, i) => {
          inp += `${pd(c.name, 16)} ${i === 0 ? pd(c.curveType, 10) : pd('', 10)} ${pd(f(pt.x, 4), 10)} ${pd(f(pt.y, 4), 10)}\n`;
        });
      } else {
        // Empty curve placeholder
        inp += `${pd(c.name, 16)} ${pd(c.curveType, 10)} 0          0\n`;
      }
      inp += `;\n`;
    });
    inp += '\n';
  }

  const xsLinks = [...cd, ...orf, ...wrs];
  if (xsLinks.length) {
    inp += `[XSECTIONS]\n;;Link           Shape        Geom1      Geom2      Geom3      Geom4      Barrels\n;;-------------- ------------ ---------- ---------- ---------- ---------- ----------\n`;
    const shapeMap: Record<number, string> = {
      1: 'CIRCULAR', 2: 'RECT_CLOSED', 3: 'HORSESHOE', 4: 'EGG', 5: 'BASKETHANDLE',
      6: 'TRAPEZOIDAL', 7: 'POWER', 8: 'IRREGULAR', 9: 'GOTHIC', 10: 'CATENARY',
      11: 'SEMIELLIPTICAL', 12: 'BASKETHANDLE', 13: 'CUSTOM', 14: 'ARCH',
      16: 'PARABOLIC', 17: 'RECT_CLOSED', 18: 'SEMICIRCULAR', 19: 'RECT_ROUND', 20: 'RECT_TRIANGULAR'
    };
    cd.forEach(l => {
      const s = shapeMap[l.nklass || 0] || 'CIRCULAR';
      if (s === 'IRREGULAR' && l.transectName) {
        inp += `${pd(l.name, 16)} ${pd('IRREGULAR', 12)} ${pd(l.transectName, 10)} 0          0          0          ${l.barrel || 1}\n`;
      } else {
        inp += `${pd(l.name, 16)} ${pd(s, 12)} ${pd(f(l.deep), 10)} ${pd(f(l.wide), 10)} 0          0          ${l.barrel || 1}\n`;
      }
    });
    orf.forEach(l => {
      const s = (l.onklass === 2) ? 'CIRCULAR' : 'RECT_CLOSED';
      const geom1 = l.dorif || l.deep || 0;
      inp += `${pd(l.name, 16)} ${pd(s, 12)} ${pd(f(geom1), 10)} 0          0          0          \n`;
    });
    wrs.forEach(l => {
      const geom1 = l.ytop ? (l.ytop - (l.ycrest || 0)) : 0;
      const geom2 = l.wlen || 0;
      inp += `${pd(l.name, 16)} RECT_OPEN    ${pd(f(geom1), 10)} ${pd(f(geom2), 10)} 0          0          \n`;
    });
    inp += '\n';
  }

  // Transects (HEC-2 format for irregular cross-sections)
  const transects = p.transects || [];
  if (transects.length) {
    inp += `[TRANSECTS]\n`;
    transects.forEach(t => {
      if (t.points.length === 0) return;
      inp += `NC  ${f(t.nLeft, 4)}  ${f(t.nRight, 4)}  ${f(t.nChannel, 4)}\n`;
      inp += `X1  ${pd(t.name, 16)} ${t.points.length}      ${f(t.leftBank, 2)}     ${f(t.rightBank, 2)}     0.0     0.0     0.0     0.0     0.0\n`;
      for (let i = 0; i < t.points.length; i += 4) {
        let gr = 'GR  ';
        for (let j = i; j < Math.min(i + 4, t.points.length); j++) {
          gr += `${f(t.points[j].elevation, 3)}  ${f(t.points[j].station, 3)}  `;
        }
        inp += gr.trimEnd() + '\n';
      }
      inp += `;\n`;
    });
    inp += '\n';
  }

  if (cd.length) {
    inp += `[LOSSES]\n;;Link           Inlet      Outlet     Average    Flap Gate\n;;-------------- ---------- ---------- ---------- ----------\n`;
    cd.forEach(l => {
      inp += `${pd(l.name, 16)} 0          0          0          NO\n`;
    });
    inp += '\n';
  }

  // Time Series
  const tsList = p.timeSeries || [];
  if (tsList.length) {
    inp += `[TIMESERIES]\n;;Name           Time       Value\n;;-------------- ---------- ----------\n`;
    tsList.forEach(ts => {
      ts.points.forEach(pt => {
        inp += `${pd(ts.name, 16)} ${pd(f(pt.time, 4), 10)} ${pd(f(pt.value, 4), 10)}\n`;
      });
      inp += `;\n`;
    });
    inp += '\n';
  }

  // Build map of node names to their time series
  const nodeToTS: Record<string, string> = {};
  tsList.forEach(ts => {
    const node = p.nodes.find(n => n.idx === ts.nodeIdx);
    if (node) nodeToTS[node.name] = ts.name;
  });

  const inflowNodes = p.nodes.filter(n => (n.qinst && n.qinst > 0) || nodeToTS[n.name]);
  if (inflowNodes.length) {
    inp += `[INFLOWS]\n;;Node           Constituent  Time Series      Type     Mfactor  Sfactor  Baseline Pattern\n;;-------------- ------------ ---------------- -------- -------- -------- -------- --------\n`;
    inflowNodes.forEach(n => {
      const tsName = nodeToTS[n.name];
      if (tsName) {
        const ts = tsList.find(t => t.name === tsName);
        const type = ts?.type || 'FLOW';
        inp += `${pd(n.name, 16)} ${pd(type, 12)} ${pd(tsName, 16)} ${pd(type, 8)} 1.0      1.0      ${f(n.qinst || 0)}\n`;
      } else {
        inp += `${pd(n.name, 16)} FLOW         ""               FLOW     1.0      1.0      ${f(n.qinst)}\n`;
      }
    });
    inp += '\n';
  }

  const cn = p.nodes.filter(n => n.x || n.y);
  if (cn.length) {
    inp += `[COORDINATES]\n;;Node           X-Coord            Y-Coord\n;;-------------- ------------------ ------------------\n`;
    cn.forEach(n => { inp += `${pd(n.name, 16)} ${pd(f(n.x, 2), 18)} ${pd(f(n.y, 2), 18)}\n`; });
    inp += '\n';

    const xs = cn.map(n => n.x), ys = cn.map(n => n.y);
    inp += `[MAP]\nDIMENSIONS ${Math.min(...xs).toFixed(2)} ${Math.min(...ys).toFixed(2)} ${Math.max(...xs).toFixed(2)} ${Math.max(...ys).toFixed(2)}\nUnits      None\n\n`;
  }

  // Subcatchments
  const subs = p.subcatchments || [];
  if (subs.length) {
    inp += `[SUBCATCHMENTS]\n;;Name           Rain Gage        Outlet           Area       %Imperv    Width      %Slope     CurbLen    SnowPack\n;;-------------- ---------------- ---------------- ---------- ---------- ---------- ---------- ---------- ----------\n`;
    subs.forEach(s => {
      inp += `${pd(s.name, 16)} ${pd(s.rainGage || '*', 16)} ${pd(s.outlet || '?', 16)} ${pd(f(s.area), 10)} ${pd(f(s.imperv), 10)} ${pd(f(s.width), 10)} ${pd(f(s.slope), 10)} 0          \n`;
    });
    inp += '\n';
  }

  if (subs.length) {
    inp += `[SUBAREAS]\n;;Subcatchment    N-Imperv   N-Perv     S-Imperv   S-Perv     PctZero    RouteTo    PctRouted\n;;-------------- ---------- ---------- ---------- ---------- ---------- ---------- ----------\n`;
    subs.forEach(s => {
      inp += `${pd(s.name, 16)} ${pd(f(s.nImperv, 4), 10)} ${pd(f(s.nPerv, 4), 10)} ${pd(f(s.dsImperv, 2), 10)} ${pd(f(s.dsPerv, 2), 10)} ${pd(f(s.pctZero), 10)} ${pd(s.routeTo || 'OUTLET', 10)} 100\n`;
    });
    inp += '\n';
  }

  // Infiltration (Horton if f0 available, else Green-Ampt if conduc, else Curve Number)
  const subsWithInfil = subs.filter(s => s.f0 > 0 || s.conduc > 0 || s.curveNum > 0);
  if (subsWithInfil.length) {
    inp += `[INFILTRATION]\n;;Subcatchment    Param1     Param2     Param3     Param4     Param5\n;;-------------- ---------- ---------- ---------- ---------- ----------\n`;
    subs.forEach(s => {
      if (s.f0 > 0) {
        // Horton
        inp += `${pd(s.name, 16)} ${pd(f(s.f0), 10)} ${pd(f(s.ff), 10)} ${pd(f(s.fDecay), 10)} ${pd(f(s.fDry), 10)} ${pd(f(s.fMaxVol), 10)}\n`;
      } else if (s.conduc > 0) {
        // Green-Ampt
        inp += `${pd(s.name, 16)} ${pd(f(s.suctionHead), 10)} ${pd(f(s.conduc), 10)} ${pd(f(s.initMoisDef), 10)} 0          0\n`;
      } else if (s.curveNum > 0) {
        // Curve Number
        inp += `${pd(s.name, 16)} ${pd(f(s.curveNum), 10)} ${pd(f(s.conduc), 10)} ${pd(f(s.fDry), 10)} 0          0\n`;
      }
    });
    inp += '\n';
  }

  // Pollutants
  const polls = p.pollutants || [];
  if (polls.length) {
    inp += `[POLLUTANTS]\n;;Name           Units  Crain      Cgw        Crdii      Kdecay     SnowOnly   CoPollutant    CoFrac\n;;-------------- ------ ---------- ---------- ---------- ---------- ---------- -------------- ----------\n`;
    polls.forEach(pol => {
      inp += `${pd(pol.name, 16)} ${pd(pol.units, 6)} ${pd(f(pol.cRain), 10)} ${pd(f(pol.cGW), 10)} ${pd(f(pol.cRDII), 10)} ${pd(f(pol.decayCoeff, 4), 10)} ${pd(pol.snowOnly ? 'YES' : 'NO', 10)} ${pd(pol.coPollutant || '*', 14)} ${pd(f(pol.coFraction), 10)}\n`;
    });
    inp += '\n';
  }

  // Land Uses
  const lus = p.landuses || [];
  if (lus.length) {
    inp += `[LANDUSES]\n;;Name           SweepInterval  SweepFraction  SweepAvail\n;;-------------- -------------- -------------- ----------\n`;
    lus.forEach(lu => {
      inp += `${pd(lu.name, 16)} ${pd(f(lu.sweepInterval), 14)} ${pd(f(lu.sweepFraction), 14)} ${pd(f(lu.sweepAvail), 10)}\n`;
    });
    inp += '\n';
  }

  // Buildup
  const bus = p.buildups || [];
  if (bus.length) {
    inp += `[BUILDUP]\n;;Landuse         Pollutant        FuncType   C1         C2         C3         PerUnit\n;;-------------- ---------------- ---------- ---------- ---------- ---------- ----------\n`;
    bus.forEach(bu => {
      inp += `${pd(bu.landuse, 16)} ${pd(bu.pollutant, 16)} ${pd(bu.funcType, 10)} ${pd(f(bu.c1), 10)} ${pd(f(bu.c2), 10)} ${pd(f(bu.c3), 10)} ${pd(bu.perUnit || 'AREA', 10)}\n`;
    });
    inp += '\n';
  }

  // Washoff
  const wos = p.washoffs || [];
  if (wos.length) {
    inp += `[WASHOFF]\n;;Landuse         Pollutant        FuncType   C1         C2         SweepEff   BMPEff\n;;-------------- ---------------- ---------- ---------- ---------- ---------- ----------\n`;
    wos.forEach(wo => {
      inp += `${pd(wo.landuse, 16)} ${pd(wo.pollutant, 16)} ${pd(wo.funcType, 10)} ${pd(f(wo.c1), 10)} ${pd(f(wo.c2), 10)} ${pd(f(wo.sweepEffic), 10)} ${pd(f(wo.bmPct), 10)}\n`;
    });
    inp += '\n';
  }

  // Loadings
  const lds = p.loadings || [];
  if (lds.length) {
    inp += `[LOADINGS]\n;;Subcatchment    Pollutant        InitBuildup\n;;-------------- ---------------- ----------\n`;
    lds.forEach(ld => {
      inp += `${pd(ld.subcatchment, 16)} ${pd(ld.pollutant, 16)} ${pd(f(ld.value), 10)}\n`;
    });
    inp += '\n';
  }

  // Controls (Real-Time Control Rules)
  const rules = p.controlRules || [];
  if (rules.length) {
    inp += `[CONTROLS]\n`;
    rules.forEach(rule => {
      inp += `RULE ${rule.name}\n`;
      rule.conditions.forEach((cond, i) => {
        const prefix = i === 0 ? 'IF' : rule.conditionLogic;
        inp += `${prefix} ${cond.variable} ${cond.id} ${cond.attribute} ${cond.relation} ${cond.value}\n`;
      });
      rule.actions.forEach(act => {
        inp += `THEN ${act.link} ${act.attribute} = ${act.value}\n`;
      });
      rule.elseActions.forEach(act => {
        inp += `ELSE ${act.link} ${act.attribute} = ${act.value}\n`;
      });
      if (rule.priority > 1) {
        inp += `PRIORITY ${rule.priority}\n`;
      }
      inp += `\n`;
    });
  }

  // LID Controls
  const lids = p.lidControls || [];
  if (lids.length) {
    inp += `[LID_CONTROLS]\n;;Name           Type/Layer   Par1       Par2       Par3       Par4       Par5       Par6       Par7\n;;-------------- ------------ ---------- ---------- ---------- ---------- ---------- ---------- ----------\n`;
    lids.forEach(lid => {
      inp += `${pd(lid.name, 16)} ${pd(lid.lidType, 12)}\n`;
      lid.layers.forEach(layer => {
        const params = layer.params.map(v => pd(f(v, 4), 10)).join(' ');
        inp += `${pd(lid.name, 16)} ${pd(layer.layerType, 12)} ${params}\n`;
      });
    });
    inp += '\n';
  }

  // LID Usage
  const lidUsages = p.lidUsages || [];
  if (lidUsages.length) {
    inp += `[LID_USAGE]\n;;Subcatchment    LID Process      Number  Area       Width      InitSat    FromImperv ToPerv     RptFile                  DrainTo\n;;-------------- ---------------- ------- ---------- ---------- ---------- ---------- ---------- ------------------------ ----------------\n`;
    lidUsages.forEach(u => {
      inp += `${pd(u.subcatchment, 16)} ${pd(u.lidControl, 16)} ${pd(String(u.number), 7)} ${pd(f(u.area), 10)} ${pd(f(u.width), 10)} ${pd(f(u.initSat), 10)} ${pd(f(u.fromImperv), 10)} ${pd(String(u.toPerv), 10)} ${pd(u.rptFile || '*', 24)} ${u.drainTo || ''}\n`;
    });
    inp += '\n';
  }

  // RDII Inflows
  const rdiiInflows = p.rdiiInflows || [];
  if (rdiiInflows.length) {
    inp += `[RDII]\n;;Node           UHgroup          SewerArea\n;;-------------- ---------------- ----------\n`;
    rdiiInflows.forEach(ri => {
      inp += `${pd(ri.nodeName, 16)} ${pd(ri.uhGroupName, 16)} ${pd(f(ri.sewerArea), 10)}\n`;
    });
    inp += '\n';
  }

  // RDII Unit Hydrographs
  const rdiiUH = p.rdiiHydrographs || [];
  if (rdiiUH.length) {
    inp += `[HYDROGRAPHS]\n;;Hydrograph      Rain Gage/Month  Response  R          T          K          Dmax       Drec       Dinit\n;;-------------- ---------------- --------- ---------- ---------- ---------- ---------- ---------- ----------\n`;
    rdiiUH.forEach(uh => {
      inp += `${pd(uh.name, 16)} ${pd(uh.rainGage, 16)}\n`;
      inp += `${pd(uh.name, 16)} ${pd(uh.months, 16)} SHORT     ${pd(f(uh.r1, 4), 10)} ${pd(f(uh.t1, 4), 10)} ${pd(f(uh.k1, 4), 10)} ${pd(f(uh.iaMax, 4), 10)} ${pd(f(uh.iaRecovery, 4), 10)} ${pd(f(uh.iaInit, 4), 10)}\n`;
      inp += `${pd(uh.name, 16)} ${pd(uh.months, 16)} MEDIUM    ${pd(f(uh.r2, 4), 10)} ${pd(f(uh.t2, 4), 10)} ${pd(f(uh.k2, 4), 10)}\n`;
      inp += `${pd(uh.name, 16)} ${pd(uh.months, 16)} LONG      ${pd(f(uh.r3, 4), 10)} ${pd(f(uh.t3, 4), 10)} ${pd(f(uh.k3, 4), 10)}\n`;
    });
    inp += '\n';
  }

  inp += `[REPORT]\nSUBCATCHMENTS ALL\nNODES ALL\nLINKS ALL\n`;
  return inp;
}

export function buildCSV(data: Record<string, unknown>[]): string {
  if (!data.length) return '';
  const ks = Object.keys(data[0]);
  let csv = ks.join(',') + '\n';
  data.forEach(r => {
    csv += ks.map(k => {
      const v = r[k];
      return v == null ? '' : typeof v === 'string' && v.includes(',') ? `"${v}"` : v;
    }).join(',') + '\n';
  });
  return csv;
}
