// ===================================================================
// XP File Generator — creates .xp card format from user-defined parameters
// Generates 80-column fixed-width card images compatible with XPSWMM
// ===================================================================

export interface MakeNode {
  id: string;
  name: string;
  x: number;
  y: number;
  elevation: number;
  maxDepth: number;
  initDepth: number;
  type: 'junction' | 'outfall' | 'storage';
  // Outfall-specific
  outfallType?: number; // 1=Free, 2=Fixed, 3=Tidal
  fixedStage?: number;
  // Storage-specific
  storageArea?: number;
}

export interface MakeLink {
  id: string;
  name: string;
  fromNode: string;
  toNode: string;
  type: 'conduit' | 'pump' | 'orifice' | 'weir';
  // Conduit
  shape?: number;     // 1=Circular, 2=Rect, etc.
  depth?: number;
  width?: number;
  length?: number;
  roughness?: number;
  usInvert?: number;
  dsInvert?: number;
  barrels?: number;
  // Pump
  pumpType?: number;  // 1-4
  pumpOnDepth?: number;
  pumpOffDepth?: number;
  pumpCurveName?: string;
  // Orifice
  orificeShape?: number; // 1=Side, 2=Circular
  orificeCoeff?: number;
  orificeDiam?: number;
  orificeOffset?: number;
  // Weir
  weirType?: number;   // 1=Transverse, 2=Side, 3=V-Notch, 4=Broad
  weirCrest?: number;
  weirTop?: number;
  weirLength?: number;
  weirCoeff?: number;
}

export interface MakeSubcatchment {
  id: string;
  name: string;
  area: number;
  width: number;
  slope: number;
  imperv: number;
  outlet: string;
  nImperv: number;
  nPerv: number;
  dsImperv: number;
  dsPerv: number;
  // Infiltration (Horton)
  f0: number;
  ff: number;
  fDecay: number;
}

export interface MakeControl {
  id: string;
  name: string;
  sensorNode: string;
  attribute: string;  // DEPTH, HEAD, FLOW
  relation: string;   // >, <, =
  threshold: number;
  actionLink: string;
  action: string;     // ON, OFF, or numeric
  elseAction: string; // ON, OFF, or empty
  priority: number;
}

export interface MakeJobControl {
  title: string;
  metric: boolean;
  routingMethod: number; // 0=DynWave, 3=Kinwave, 4=Difwave
  timeStep: number;      // seconds
  maxTrials: number;
  headTolerance: number;
}

export interface MakeModel {
  jobControl: MakeJobControl;
  nodes: MakeNode[];
  links: MakeLink[];
  subcatchments: MakeSubcatchment[];
  controls: MakeControl[];
}

// Pad string to fixed width (left-aligned)
function pad(s: string | number, w: number): string {
  return String(s).substring(0, w).padEnd(w);
}

// Format number to fixed width
function num(v: number, w: number, d = 2): string {
  const s = v.toFixed(d);
  return s.substring(0, w).padStart(w);
}

// Build a single 80-col card line
function card(group: string, sub: number, cardId: string, seq: number, oi: number, data: string): string {
  // Format: GRPP SSSS CCCC SEQQ  OI  DATA...
  // Group=4, Sub=4, Card=4, Seq=4, OI=4, data=rest (up to col 80)
  const g = pad(group, 4);
  const s = String(sub).padStart(4);
  const c = pad(cardId, 4);
  const q = String(seq).padStart(4);
  const o = String(oi).padStart(4);
  const line = `${g}${s} ${c}${q} ${o}  ${data}`;
  return line.padEnd(80).substring(0, 80);
}

export function generateXP(model: MakeModel): string {
  const lines: string[] = [];
  const jc = model.jobControl;
  
  // Header comment
  lines.push(`;; XPSWMM .xp file generated by XP Model Builder`);
  lines.push(`;; Title: ${jc.title || 'Untitled Model'}`);
  lines.push(`;; Generated: ${new Date().toISOString()}`);
  lines.push('');

  // Job Control cards (EXTR group)
  // A1 - Title
  const titleData = pad(jc.title || 'Generated Model', 75);
  lines.push(card('EXTR', 0, 'A1', 1, 0, `    ${titleData}`));

  // B1 - Time step
  const deltData = `         ${num(jc.timeStep, 6, 1)}`;
  lines.push(card('EXTR', 0, 'B1', 1, 0, deltData.padEnd(55)));

  // B2 - Metric flag
  const metricFlag = jc.metric ? '1' : '0';
  lines.push(card('EXTR', 0, 'B2', 1, 0, `   ${metricFlag}`));

  // BB2 - Solver settings
  const bb2Data = `     ${num(jc.maxTrials, 8, 0)}${num(jc.headTolerance, 8, 4)}${''.padEnd(30)}${''.padEnd(15)}${num(0, 8, 0)}${''.padEnd(1)}${String(jc.routingMethod)}`;
  lines.push(card('EXTR', 0, 'BB2', 1, 0, bb2Data));

  lines.push('');

  // Node names (ZZZN:NODE cards)
  model.nodes.forEach((n, i) => {
    const oi = i + 1;
    lines.push(card('ZZZN', 0, 'NODE', 1, oi, pad(n.name, 20)));
  });
  lines.push('');

  // Node coordinates and properties (SP1N cards)
  model.nodes.forEach((n, i) => {
    const oi = i + 1;
    // SP1N: cols 6-17=X, 18-29=Y, 50=outfall flag, 62-71=name
    const outfFlag = n.type === 'outfall' ? '1' : '0';
    const sp1nData = `    ${num(n.x, 12, 2)}${num(n.y, 12, 2)}${''.padEnd(20)}${outfFlag}${''.padEnd(11)}${pad(n.name, 10)}`;
    lines.push(card('EXTR', 0, 'SP1N', 1, oi, sp1nData));
  });
  lines.push('');

  // Node D1 cards (elevation, depth, inflow)
  model.nodes.forEach((n, i) => {
    const oi = i + 1;
    // D1: cols 13-20=GRELEV, 31-38=QINST, 40-46=Y0
    const d1Data = `            ${num(n.elevation, 8, 2)}${''.padEnd(10)}${num(0, 8, 2)}${num(n.initDepth, 7, 2)}`;
    lines.push(card('EXTR', 0, 'D1', 1, oi, d1Data));
  });
  lines.push('');

  // Node E1 cards (max depth / storage)
  model.nodes.forEach((n, i) => {
    const oi = i + 1;
    const ztop = n.elevation + n.maxDepth;
    const astore = n.type === 'storage' ? (n.storageArea || 0) : 0;
    const e1Data = `            ${num(ztop, 7, 2)}${num(astore, 7, 2)}`;
    lines.push(card('EXTR', 0, 'E1', 1, oi, e1Data));
  });
  lines.push('');

  // Outfall J3 cards
  const outfalls = model.nodes.filter(n => n.type === 'outfall');
  outfalls.forEach(n => {
    const oi = model.nodes.indexOf(n) + 1;
    const ko = n.outfallType || 1;
    const delta = n.fixedStage || 0;
    const j3Data = `   ${ko}      ${num(delta, 8, 2)}`;
    lines.push(card('EXTR', 0, 'J3', 1, oi, j3Data));
  });
  if (outfalls.length) lines.push('');

  // Link name cards (ZZZE:LINK or SPDN)
  const nodeNameMap: Record<string, number> = {};
  model.nodes.forEach((n, i) => { nodeNameMap[n.name] = i + 1; });

  model.links.forEach((l, i) => {
    const oi = i + 1;
    // SPDN: cols 1-10=name1(us), 11-20=name2(ds), 21-30=name3, 31-40=name4
    const usName = l.fromNode;
    const dsName = l.toNode;
    const spdnData = pad(usName, 10) + pad(dsName, 10) + pad('', 10) + pad('', 10);
    lines.push(card('EXTR', 0, 'SPDN', 1, oi, spdnData));
  });
  lines.push('');

  // SPDV - link type flags
  model.links.forEach((l, i) => {
    const oi = i + 1;
    const isCond = l.type === 'conduit' ? '1' : '0';
    const isPump = l.type === 'pump' ? '1' : '0';
    const isOrif = l.type === 'orifice' ? '1' : '0';
    const isWeir = l.type === 'weir' ? '1' : '0';
    const spdvData = `${isCond}      ${isPump}      ${isOrif}      ${isWeir}`;
    lines.push(card('EXTR', 0, 'SPDV', 1, oi, spdvData));
  });
  lines.push('');

  // Conduit C1 cards
  const conduits = model.links.filter(l => l.type === 'conduit');
  conduits.forEach(l => {
    const oi = model.links.indexOf(l) + 1;
    const shape = l.shape || 1;
    const deep = l.depth || 1;
    const wide = l.width || 0;
    const len = l.length || 100;
    const zp1 = l.usInvert || 0;
    const zp2 = l.dsInvert || 0;
    const rough = l.roughness || 0.013;
    // C1: cols 13-14=NKLASS, 25-31=DEEP, 34-40=WIDE, 43-50=LEN, 52-59=ZP1, 61-68=ZP2, 70-79=ROUGH
    const c1Data = `            ${num(shape, 2, 0)}${''.padEnd(8)}${num(deep, 7, 3)}${num(wide, 7, 3)}  ${num(len, 8, 2)}${num(zp1, 8, 2)}  ${num(zp2, 8, 2)}${num(rough, 10, 4)}`;
    lines.push(card('EXTR', 0, 'C1', 1, oi, c1Data));
  });
  if (conduits.length) {
    // C6 - barrels
    conduits.forEach(l => {
      const oi = model.links.indexOf(l) + 1;
      const barrels = l.barrels || 1;
      lines.push(card('EXTR', 0, 'C6', 1, oi, `${''.padEnd(62)}${num(barrels, 8, 0)}`));
    });
    lines.push('');
  }

  // Pump H1A cards
  const pumps = model.links.filter(l => l.type === 'pump');
  pumps.forEach(l => {
    const oi = model.links.indexOf(l) + 1;
    const iptyp = l.pumpType || 2;
    const pon = l.pumpOnDepth || 0;
    const poff = l.pumpOffDepth || 0;
    const psel = l.pumpCurveName || `PC_${l.name}`;
    const h1aData = `${num(iptyp, 2, 0)}${''.padEnd(8)}${num(pon, 8, 2)}${num(poff, 8, 2)}${''.padEnd(21)}${pad(psel, 20)}`;
    lines.push(card('EXTR', 0, 'H1A', 1, oi, h1aData));
  });
  if (pumps.length) lines.push('');

  // Orifice F1 cards
  const orifices = model.links.filter(l => l.type === 'orifice');
  orifices.forEach(l => {
    const oi = model.links.indexOf(l) + 1;
    const onklass = l.orificeShape || 2;
    const corif = l.orificeCoeff || 0.65;
    const dorif = l.orificeDiam || 1;
    const zp = l.orificeOffset || 0;
    const f1Data = `${''.padEnd(18)}${onklass}  ${num(0, 6, 2)}${num(corif, 4, 2)}${num(zp, 7, 2)}${num(dorif, 10, 3)}`;
    lines.push(card('EXTR', 0, 'F1', 1, oi, f1Data));
  });
  if (orifices.length) lines.push('');

  // Weir G1 cards
  const weirs = model.links.filter(l => l.type === 'weir');
  weirs.forEach(l => {
    const oi = model.links.indexOf(l) + 1;
    const kweir = l.weirType || 1;
    const ycrest = l.weirCrest || 0;
    const ytop = l.weirTop || 1;
    const wlen = l.weirLength || 1;
    const coeff = l.weirCoeff || 1.84;
    const g1Data = `${''.padEnd(17)}${kweir}  ${num(ycrest, 8, 2)}${num(ytop, 8, 2)}${''.padEnd(3)}${num(wlen, 6, 2)}${''.padEnd(3)}${num(coeff, 4, 2)}`;
    lines.push(card('EXTR', 0, 'G1', 1, oi, g1Data));
  });
  if (weirs.length) lines.push('');

  // Subcatchments (RNFF group)
  model.subcatchments.forEach((sc, i) => {
    const oi = i + 1;
    // R1: name, area, width, slope, imperv, outlet
    const r1Data = `${pad(sc.name, 10)}${num(sc.area, 10, 2)}${num(sc.width, 10, 2)}${num(sc.slope, 10, 4)}${num(sc.imperv, 10, 2)}${pad(sc.outlet, 10)}`;
    lines.push(card('RNFF', 0, 'R1', 1, oi, r1Data));
    // R2: Manning's n, depression storage
    const r2Data = `${num(sc.nImperv, 10, 4)}${num(sc.nPerv, 10, 4)}${num(sc.dsImperv, 10, 4)}${num(sc.dsPerv, 10, 4)}${num(0, 10, 2)}`;
    lines.push(card('RNFF', 0, 'R2', 1, oi, r2Data));
    // R3: Infiltration (Horton)
    if (sc.f0 > 0) {
      const r3Data = `${num(sc.f0, 10, 4)}${num(sc.ff, 10, 4)}${num(sc.fDecay, 10, 4)}`;
      lines.push(card('RNFF', 0, 'R3', 1, oi, r3Data));
    }
  });
  if (model.subcatchments.length) lines.push('');

  // Controls (CONF group)
  model.controls.forEach((ctrl, i) => {
    const oi = i + 1;
    // C1: rule name and priority
    lines.push(card('CONF', 0, 'C1', 1, oi, `${pad(ctrl.name, 20)}${num(ctrl.priority, 4, 0)}`));
    // C2: condition
    const c2Data = `NODE   ${pad(ctrl.sensorNode, 16)}${pad(ctrl.attribute, 10)}${pad(ctrl.relation, 4)}${num(ctrl.threshold, 10, 4)}`;
    lines.push(card('CONF', 0, 'C2', 1, oi, c2Data));
    // C3: action
    const c3Data = `${pad(ctrl.actionLink, 16)}STATUS  ${pad(ctrl.action, 10)}`;
    if (ctrl.elseAction) {
      const elseData = `ELSE ${pad(ctrl.actionLink, 16)}STATUS  ${pad(ctrl.elseAction, 10)}`;
      lines.push(card('CONF', 0, 'C3', 1, oi, c3Data + elseData));
    } else {
      lines.push(card('CONF', 0, 'C3', 1, oi, c3Data));
    }
  });
  if (model.controls.length) lines.push('');

  return lines.join('\n') + '\n';
}

// Generate default empty model
export function createDefaultModel(): MakeModel {
  return {
    jobControl: {
      title: 'New SWMM Model',
      metric: false,
      routingMethod: 0,
      timeStep: 30,
      maxTrials: 8,
      headTolerance: 0.005,
    },
    nodes: [],
    links: [],
    subcatchments: [],
    controls: [],
  };
}
