// ===================================================================
// XP File Generator — creates .xp card format from user-defined parameters
// Generates 80-column fixed-width card images compatible with XPSWMM
// ===================================================================

export interface MakeNode {
  id: string;
  name: string;
  x: number;
  y: number;
  elevation: number;
  maxDepth: number;
  initDepth: number;
  type: 'junction' | 'outfall' | 'storage';
  // Outfall-specific
  outfallType?: number; // 1=Free, 2=Fixed, 3=Tidal
  fixedStage?: number;
  // Storage-specific
  storageArea?: number;
}

export interface MakeLink {
  id: string;
  name: string;
  fromNode: string;
  toNode: string;
  type: 'conduit' | 'pump' | 'orifice' | 'weir';
  // Conduit
  shape?: number;     // 1=Circular, 2=Rect, etc.
  depth?: number;
  width?: number;
  length?: number;
  roughness?: number;
  usInvert?: number;
  dsInvert?: number;
  barrels?: number;
  // Pump
  pumpType?: number;  // 1-4
  pumpOnDepth?: number;
  pumpOffDepth?: number;
  pumpCurveName?: string;
  // Orifice
  orificeShape?: number; // 1=Side, 2=Circular
  orificeCoeff?: number;
  orificeDiam?: number;
  orificeOffset?: number;
  // Weir
  weirType?: number;   // 1=Transverse, 2=Side, 3=V-Notch, 4=Broad
  weirCrest?: number;
  weirTop?: number;
  weirLength?: number;
  weirCoeff?: number;
}

export interface MakeSubcatchment {
  id: string;
  name: string;
  area: number;
  width: number;
  slope: number;
  imperv: number;
  outlet: string;
  nImperv: number;
  nPerv: number;
  dsImperv: number;
  dsPerv: number;
  // Infiltration (Horton)
  f0: number;
  ff: number;
  fDecay: number;
}

export interface MakeControl {
  id: string;
  name: string;
  sensorNode: string;
  attribute: string;  // DEPTH, HEAD, FLOW
  relation: string;   // >, <, =
  threshold: number;
  actionLink: string;
  action: string;     // ON, OFF, or numeric
  elseAction: string; // ON, OFF, or empty
  priority: number;
}

export interface MakeJobControl {
  title: string;
  metric: boolean;
  routingMethod: number; // 0=DynWave, 3=Kinwave, 4=Difwave
  timeStep: number;      // seconds
  maxTrials: number;
  headTolerance: number;
}

export interface MakeModel {
  jobControl: MakeJobControl;
  nodes: MakeNode[];
  links: MakeLink[];
  subcatchments: MakeSubcatchment[];
  controls: MakeControl[];
}

// Pad string to fixed width (left-aligned)
function pad(s: string | number, w: number): string {
  return String(s).substring(0, w).padEnd(w);
}

// Format number to fixed width (right-aligned)
function num(v: number, w: number, d = 2): string {
  const s = v.toFixed(d);
  return s.substring(0, w).padStart(w);
}

// Build a fixed-width card line matching parser column expectations
// Parser reads: grp[0:4] sub[4:8] card[8:12] seq[12:16] oi[16:20]
// Data offset: ZZZN/ZZZE=24, others=25
function card(group: string, sub: number, cardId: string, seq: number, oi: number, data: string): string {
  const g = pad(group, 4);
  const s = String(sub).padStart(4);
  const c = pad(cardId, 4);
  const q = String(seq).padStart(4);
  const o = String(oi).padStart(4);
  const isZZZ = group === 'ZZZN' || group === 'ZZZE';
  const gap = isZZZ ? '    ' : '     '; // 4 or 5 chars to reach doff 24/25
  const line = `${g}${s}${c}${q}${o}${gap}${data}`;
  // Pad to minimum 80 but do NOT truncate — fields like ROUGH extend beyond col 80
  return line.length >= 80 ? line : line.padEnd(80);
}

export function generateXP(model: MakeModel): string {
  const lines: string[] = [];
  const jc = model.jobControl;
  
  // Header comment
  lines.push(`;; XPSWMM .xp file generated by XP Model Builder`);
  lines.push(`;; Title: ${jc.title || 'Untitled Model'}`);
  lines.push(`;; Generated: ${new Date().toISOString()}`);
  lines.push('');

  // Job Control cards (EXTR group)
  // A1 - Title (ALPHA p=5, w=75)
  lines.push(card('EXTR', 0, 'A1', 1, 0, `    ${pad(jc.title || 'Generated Model', 75)}`));

  // B1 - Time step (DELT p=10, w=6)
  lines.push(card('EXTR', 0, 'B1', 1, 0, `         ${num(jc.timeStep, 6, 1)}`));

  // B2 - Metric flag (METRIC p=4, w=1)
  lines.push(card('EXTR', 0, 'B2', 1, 0, `   ${jc.metric ? '1' : '0'}`));

  // BB2 - Solver settings (MFAIL p=6, FUDGE p=15, KINE p=79)
  const bb2 = ''.padEnd(5) + num(jc.maxTrials, 8, 0) + ' ' + num(jc.headTolerance, 8, 4) + ''.padEnd(56) + String(jc.routingMethod);
  lines.push(card('EXTR', 0, 'BB2', 1, 0, bb2));

  lines.push('');

  // Node names (ZZZN:NODE cards) — doff=24, parser reads data[0:14] for name
  model.nodes.forEach((n, i) => {
    lines.push(card('ZZZN', 0, 'NODE', 1, i + 1, pad(n.name, 20)));
  });
  lines.push('');

  // SP1N cards (NODX p=6/w=12, NODY p=18/w=12, FLGOUTF p=50/w=1, NODNAM p=62/w=10)
  model.nodes.forEach((n, i) => {
    const outf = n.type === 'outfall' ? '1' : '0';
    const sp = ''.padEnd(5) + num(n.x, 12, 2) + num(n.y, 12, 2) + ''.padEnd(20) + outf + ''.padEnd(11) + pad(n.name, 10);
    lines.push(card('EXTR', 0, 'SP1N', 1, i + 1, sp));
  });
  lines.push('');

  // D1 cards (GRELEV p=13/w=8, QINST p=31/w=8, Y0 p=40/w=7)
  model.nodes.forEach((n, i) => {
    const d1 = ''.padEnd(12) + num(n.elevation, 8, 2) + ''.padEnd(10) + num(0, 8, 2) + ' ' + num(n.initDepth, 7, 2);
    lines.push(card('EXTR', 0, 'D1', 1, i + 1, d1));
  });
  lines.push('');

  // E1 cards (ZTOP p=13/w=7, ASTORE p=21/w=7)
  model.nodes.forEach((n, i) => {
    const ztop = n.elevation + n.maxDepth;
    const astore = n.type === 'storage' ? (n.storageArea || 0) : 0;
    const e1 = ''.padEnd(12) + num(ztop, 7, 2) + ' ' + num(astore, 7, 2);
    lines.push(card('EXTR', 0, 'E1', 1, i + 1, e1));
  });
  lines.push('');

  // J3 cards for outfalls (KO p=4/w=1, DELTA p=11/w=8)
  const outfalls = model.nodes.filter(n => n.type === 'outfall');
  outfalls.forEach(n => {
    const oi = model.nodes.indexOf(n) + 1;
    const j3 = ''.padEnd(3) + (n.outfallType || 1) + ''.padEnd(6) + num(n.fixedStage || 0, 8, 2);
    lines.push(card('EXTR', 0, 'J3', 1, oi, j3));
  });
  if (outfalls.length) lines.push('');

  // SPDN cards (CNAME1 p=1/w=10=linkName, CNAME2 p=11/w=10=usNode, CNAME3 p=21/w=10=dsNode)
  model.links.forEach((l, i) => {
    const spdn = pad(l.name, 10) + pad(l.fromNode, 10) + pad(l.toNode, 10) + pad('', 10);
    lines.push(card('EXTR', 0, 'SPDN', 1, i + 1, spdn));
  });
  lines.push('');

  // SPDV cards (COND1 p=1, PUMP1 p=8, ORIF1 p=15, WEIR1 p=22)
  model.links.forEach((l, i) => {
    const isCond = l.type === 'conduit' ? '1' : '0';
    const isPump = l.type === 'pump' ? '1' : '0';
    const isOrif = l.type === 'orifice' ? '1' : '0';
    const isWeir = l.type === 'weir' ? '1' : '0';
    const spdv = isCond + ''.padEnd(6) + isPump + ''.padEnd(6) + isOrif + ''.padEnd(6) + isWeir;
    lines.push(card('EXTR', 0, 'SPDV', 1, i + 1, spdv));
  });
  lines.push('');

  // C1 cards (NKLASS p=13/w=2, DEEP p=25/w=7, WIDE p=34/w=7, LEN p=43/w=8, ZP1 p=52/w=8, ZP2 p=61/w=8, ROUGH p=70/w=10)
  const conduits = model.links.filter(l => l.type === 'conduit');
  conduits.forEach(l => {
    const oi = model.links.indexOf(l) + 1;
    const c1 = ''.padEnd(12) + num(l.shape || 1, 2, 0) + ''.padEnd(10)
      + num(l.depth || 1, 7, 3) + ''.padEnd(2) + num(l.width || 0, 7, 3) + ''.padEnd(2)
      + num(l.length || 100, 8, 2) + ''.padEnd(2) + num(l.usInvert || 0, 8, 2)
      + ' ' + num(l.dsInvert || 0, 8, 2) + ' ' + num(l.roughness || 0.013, 10, 4);
    lines.push(card('EXTR', 0, 'C1', 1, oi, c1));
  });
  if (conduits.length) {
    // C6 - barrels (BARREL p=67/w=8)
    conduits.forEach(l => {
      const oi = model.links.indexOf(l) + 1;
      lines.push(card('EXTR', 0, 'C6', 1, oi, ''.padEnd(66) + num(l.barrels || 1, 8, 0)));
    });
    lines.push('');
  }

  // H1A cards (IPTYP p=1/w=2, PON p=11/w=8, POFF p=19/w=8, PSEL p=51/w=20)
  const pumps = model.links.filter(l => l.type === 'pump');
  pumps.forEach(l => {
    const oi = model.links.indexOf(l) + 1;
    const psel = l.pumpCurveName || `PC_${l.name}`;
    const h1a = num(l.pumpType || 2, 2, 0) + ''.padEnd(8) + num(l.pumpOnDepth || 0, 8, 2)
      + num(l.pumpOffDepth || 0, 8, 2) + ''.padEnd(24) + pad(psel, 20);
    lines.push(card('EXTR', 0, 'H1A', 1, oi, h1a));
  });
  if (pumps.length) lines.push('');

  // F1 cards (ONKLASS p=23/w=1, AORIF p=25/w=6, CORIF p=32/w=4, ZP p=37/w=7, DORIF p=45/w=10)
  const orifices = model.links.filter(l => l.type === 'orifice');
  orifices.forEach(l => {
    const oi = model.links.indexOf(l) + 1;
    const f1 = ''.padEnd(22) + (l.orificeShape || 2) + ' ' + num(0, 6, 2)
      + ' ' + num(l.orificeCoeff || 0.65, 4, 2) + ' ' + num(l.orificeOffset || 0, 7, 2)
      + ' ' + num(l.orificeDiam || 1, 10, 3);
    lines.push(card('EXTR', 0, 'F1', 1, oi, f1));
  });
  if (orifices.length) lines.push('');

  // G1 cards (KWEIR p=22/w=1, YCREST p=24/w=8, YTOP p=33/w=8, WLEN p=44/w=6, COEFF p=53/w=4)
  const weirs = model.links.filter(l => l.type === 'weir');
  weirs.forEach(l => {
    const oi = model.links.indexOf(l) + 1;
    const g1 = ''.padEnd(21) + (l.weirType || 1) + ' ' + num(l.weirCrest || 0, 8, 2)
      + ' ' + num(l.weirTop || 1, 8, 2) + ''.padEnd(3) + num(l.weirLength || 1, 6, 2)
      + ''.padEnd(3) + num(l.weirCoeff || 1.84, 4, 2);
    lines.push(card('EXTR', 0, 'G1', 1, oi, g1));
  });
  if (weirs.length) lines.push('');

  // Subcatchments (RNFF group) — field positions all 10-char wide at p=1,11,21,31,41,51
  model.subcatchments.forEach((sc, i) => {
    const oi = i + 1;
    const r1 = pad(sc.name, 10) + num(sc.area, 10, 2) + num(sc.width, 10, 2) + num(sc.slope, 10, 4) + num(sc.imperv, 10, 2) + pad(sc.outlet, 10);
    lines.push(card('RNFF', 0, 'R1', 1, oi, r1));
    const r2 = num(sc.nImperv, 10, 4) + num(sc.nPerv, 10, 4) + num(sc.dsImperv, 10, 4) + num(sc.dsPerv, 10, 4) + num(0, 10, 2);
    lines.push(card('RNFF', 0, 'R2', 1, oi, r2));
    if (sc.f0 > 0) {
      const r3 = num(sc.f0, 10, 4) + num(sc.ff, 10, 4) + num(sc.fDecay, 10, 4);
      lines.push(card('RNFF', 0, 'R3', 1, oi, r3));
    }
  });
  if (model.subcatchments.length) lines.push('');

  // Controls (CONF group) — parser splits by whitespace
  model.controls.forEach((ctrl, i) => {
    const oi = i + 1;
    lines.push(card('CONF', 0, 'C1', 1, oi, `${pad(ctrl.name, 20)}${num(ctrl.priority, 4, 0)}`));
    const c2 = `NODE   ${pad(ctrl.sensorNode, 16)}${pad(ctrl.attribute, 10)}${pad(ctrl.relation, 4)}${num(ctrl.threshold, 10, 4)}`;
    lines.push(card('CONF', 0, 'C2', 1, oi, c2));
    const c3 = `${pad(ctrl.actionLink, 16)}STATUS  ${pad(ctrl.action, 10)}`;
    if (ctrl.elseAction) {
      lines.push(card('CONF', 0, 'C3', 1, oi, c3 + `ELSE ${pad(ctrl.actionLink, 16)}STATUS  ${pad(ctrl.elseAction, 10)}`));
    } else {
      lines.push(card('CONF', 0, 'C3', 1, oi, c3));
    }
  });
  if (model.controls.length) lines.push('');

  return lines.join('\n') + '\n';
}

// Generate default empty model
export function createDefaultModel(): MakeModel {
  return {
    jobControl: {
      title: 'New SWMM Model',
      metric: false,
      routingMethod: 0,
      timeStep: 30,
      maxTrials: 8,
      headTolerance: 0.005,
    },
    nodes: [],
    links: [],
    subcatchments: [],
    controls: [],
  };
}
